language: python

# We say we use Python 3.5 otherwise we only access by default
# to Python 2.7, 3.2, 3.3, & 3.4

python: 3.5

services:
  - memcached
  - redis-server

addons:
  postgresql: 9.4

env:
  - TOXENV=py2.7-django1.8-postgrespool-redis
  - TOXENV=py2.7-django1.8-postgrespool-memcached
  - TOXENV=py2.7-django1.8-postgrespool-pylibmc
  - TOXENV=py2.7-django1.8-postgrespool-locmem
  - TOXENV=py2.7-django1.8-postgrespool-filebased

sudo: false

install: pip install tox coveralls

before_script:
  - psql -c 'CREATE USER cachalot SUPERUSER;' -U postgres
  - psql -c 'CREATE DATABASE cachalot OWNER cachalot;' -U postgres

script: tox -e $TOXENV

after_success: coveralls
